-- AlterTable
ALTER TABLE "Clase" ALTER COLUMN "titulo" SET DATA TYPE VARCHAR(150);

-- AlterTable
ALTER TABLE "Curso" ALTER COLUMN "nombre" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "Docente" ALTER COLUMN "nombres" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "apellidos" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Rol" ALTER COLUMN "nombre_rol" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Usuario" ALTER COLUMN "nombres" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "apellidos" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "nombre_usuario" SET DATA TYPE VARCHAR(70);
